name: Acceptance Tests

on:
  pull_request:
    branches:
      - develop
      - "[0-9]+.[0-9]+"
  push:
    branches:
      - develop
      - "[0-9]+.[0-9]+"
  release:

jobs:
  acceptance-tests:
    name: Acceptance Tests PHP ${{ matrix.versions.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        versions:
          - php: "8.1"
          - php: "8.2"

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP ${{ matrix.versions.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.versions.php }}"
          coverage: pcov

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.versions.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.versions.php }}
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: make install

      - name: Check Code Style
        run: make check-style

      - name: Run Static Analysis
        run: make static-check

      - name: Run Unit & Functional Tests
        run: make coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
